sudo: required
dist: trusty

language: python

python:
  - 3.6.3

before_install:
  - cd app/react/
  - npm install
  - npm run-script build
  - cd ../..

install:
  - pip install -r requirements.txt

script: python3 manage.py test

notifications:
   slack: socialproofapp:kWI4DeCupHOV3Kvd9fPZOTtd