# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 19:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModalTextSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_text_id', models.CharField(max_length=200, unique=True)),
                ('modal_text_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('qty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, unique=True)),
                ('permanent_token', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_back', models.PositiveIntegerField(default=1440, validators=[django.core.validators.MaxValueValidator(100)])),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stores')),
            ],
        ),
        migrations.AddField(
            model_name='productviews',
            name='store_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stores'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stores'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='store_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stores'),
        ),
        migrations.AddField(
            model_name='modal',
            name='modal_text_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ModalTextSettings'),
        ),
        migrations.AddField(
            model_name='modal',
            name='store_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stores'),
        ),
        migrations.AlterUniqueTogether(
            name='productviews',
            unique_together=set([('store_name', 'product_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('store_name', 'product_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set([('store_name', 'product_id', 'order_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='modal',
            unique_together=set([('store_name', 'modal_text_id')]),
        ),
    ]
