# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 23:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='look_back',
            field=models.PositiveIntegerField(default=1440, validators=[django.core.validators.MaxValueValidator(44640)]),
        ),
    ]
