# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171116_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
