# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orders_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
