# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171124_0154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productviews',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productviews',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productviews',
            name='store',
        ),
        migrations.DeleteModel(
            name='ProductViews',
        ),
    ]
