# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171125_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modal',
            name='color',
        ),
        migrations.RemoveField(
            model_name='modal',
            name='duration',
        ),
        migrations.AddField(
            model_name='modal',
            name='color_brightness',
            field=models.FloatField(default=0.487),
        ),
        migrations.AddField(
            model_name='modal',
            name='color_hue',
            field=models.FloatField(default=83.28),
        ),
        migrations.AddField(
            model_name='modal',
            name='color_saturation',
            field=models.FloatField(default=0.306),
        ),
        migrations.AddField(
            model_name='modal',
            name='size',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='modal',
            name='social_setting',
            field=models.TextField(default=''),
        ),
    ]
