# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171125_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modal',
            name='size',
            field=models.TextField(default='250,100'),
        ),
        migrations.AlterField(
            model_name='modal',
            name='social_setting',
            field=models.TextField(default='latest'),
        ),
    ]
