# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171125_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modal',
            name='location',
            field=models.CharField(default='bottom-right', max_length=200),
        ),
    ]
