# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171125_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.TextField()),
                ('snapshot_date', models.DateField(blank=True, null=True)),
                ('view_count', models.IntegerField()),
                ('method', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='apimetrics',
            unique_together=set([('snapshot_date', 'view')]),
        ),
    ]
