# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171127_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimetrics',
            name='method',
            field=models.TextField(),
        ),
    ]
