# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171127_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.TextField(default=''),
        ),
    ]
