# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20171129_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set([('product', 'collection_id')]),
        ),
    ]
