# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20171129_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.IntegerField()),
                ('snapshot_date', models.DateField(blank=True, null=True)),
                ('product_id_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_from', to='app.Product')),
                ('product_id_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_to', to='app.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='modalmetrics',
            unique_together=set([('snapshot_date', 'store', 'product_id_from', 'product_id_to')]),
        ),
    ]
