# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_modal_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modal',
            old_name='scope',
            new_name='social_scope',
        ),
    ]
