# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20171201_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modal',
            name='location',
            field=models.CharField(default='bottom-left', max_length=200),
        ),
    ]
