# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20171201_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shopify_api_scope',
            field=models.TextField(default=''),
        ),
    ]
