# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_store_shopify_api_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(default='')),
                ('webhook_id', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='webhooks',
            unique_together=set([('store', 'webhook_id')]),
        ),
    ]
