# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20171219_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhooks',
            unique_together=set([('store', 'topic')]),
        ),
    ]
